# Generated by Django 3.1.7 on 2021-03-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210320_0708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name', 'birth_date')},
        ),
    ]
